# Generated by Django 4.1.3 on 2022-12-06 08:49

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(default=cards.models.gen_series, max_length=2, verbose_name='Серия')),
                ('number', models.CharField(default=cards.models.gen_number, max_length=6, verbose_name='Номер')),
                ('data_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('data_end', models.DateTimeField(default=cards.models.gen_time, verbose_name='Дата выпуска')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего использования')),
                ('summ', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('не активирована', 'не активирована'), ('активирована', 'активирована'), ('просрочена', 'просрочена')], default='не активирована', max_length=15, verbose_name='Статус карты')),
            ],
        ),
    ]
