# Generated by Django 4.1.3 on 2022-12-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_cards_data_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='series',
            field=models.CharField(default='AA', max_length=2, verbose_name='Серия'),
        ),
    ]
