# Generated by Django 4.1.3 on 2022-12-06 09:16

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_cards_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='series',
            field=models.CharField(default=cards.models.gen_series, max_length=2, verbose_name='Серия'),
        ),
    ]
