# Generated by Django 4.1.3 on 2022-12-06 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_cards_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='data_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выпуска'),
        ),
    ]
