# Generated by Django 4.1.3 on 2022-12-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cards_data_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='data_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска'),
        ),
    ]
