# Generated by Django 4.1.3 on 2022-12-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_cards_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='number',
            field=models.CharField(max_length=6, verbose_name='Номер'),
        ),
    ]
