# Generated by Django 4.1.3 on 2022-12-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_name',
            new_name='quiz',
        ),
    ]
