# Generated by Django 4.1.3 on 2022-12-05 21:06

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_answer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, validators=[questions.models.validate_even]),
        ),
    ]
